.MODEL	SMALL
; I/O ADDRESS BUS DECODE - EVERY DEVICE GETS 0X200 ADDRESSES */
IO0  EQU  0000H
IO1  EQU  0200H
IO2  EQU  0400H
IO3  EQU  0600H
IO4  EQU  0800H
IO5  EQU  0A00H
IO6  EQU  0C00H
IO7  EQU  0E00H
IO8  EQU  1000H
IO9  EQU  1200H
IO10 EQU  1400H
IO11 EQU  1600H
IO12 EQU  1800H
IO13 EQU  1A00H
IO14 EQU  1C00H
IO15 EQU  1E00H

; 8251A USART 
ADR_USART_DATA EQU  (IO6 + 00H)
;ONDE VOCE VAI MANDAR E RECEBER DADOS DO 8251

ADR_USART_CMD  EQU  (IO6 + 02H)
;É O LOCAL ONDE VOCE VAI ESCREVER PARA PROGRAMAR O 8251

ADR_USART_STAT EQU  (IO6 + 02H)
;RETORNA O STATUS SE UM CARACTER FOI DIGITADO
;RETORNA O STATUS SE POSSO TRANSMITIR CARACTER PARA O TERMINAL

;NUMEROS
DIG0 = 10111111B ;DEC = 191
DIG1 = 10000110B ;DEC = 134
DIG2 = 11011011B ;DEC = 219
DIG3 = 11001111B ;DEC = 207
DIG4 = 11100110B ;DEC = 230
DIG5 = 11101101B ;DEC = 237
DIG6 = 11111101B ;DEC = 253
DIG7 = 10000111B ;DEC = 135
DIG8 = 11111111B ;DEC = 255
DIG9 = 11101111B ;DEC = 239


TIMER_COUNTER0	EQU 00H
TIMER_COUNTER1	EQU 40H
TIMER_COUNTER2	EQU 80H

ADR_TIMER_DATA0   EQU  (IO3 + 00H)
ADR_TIMER_DATA1   EQU  (IO3 + 02H)
ADR_TIMER_DATA2   EQU  (IO3 + 04H)
ADR_TIMER_CONTROL EQU  (IO3 + 06H)

TIMER_LATCH	  EQU 00H
TIMER_LSB	  EQU 10H
TIMER_MSB	  EQU 20H
TIMER_LSB_MSB 	  EQU 30H

TIMER_MODE0	EQU 00H
TIMER_MODE1	EQU 02H
TIMER_MODE2	EQU 04H
TIMER_MODE3	EQU 06H
TIMER_MODE4	EQU 08H
TIMER_MODE5	EQU 09H
TIMER_BCD	EQU 01H


.8086
.CODE
   ;ASSUME    CS:CODE,DS:DATA
   ORG 0008H
   PONTEIRO_TRATADOR_INTERRUPCAO DB 4 DUP(?) ; PONTEIRO PARA INTERRUPCAO
   ;APONTA PARA UMA ROTINA CHAMADA A CADA 1 SEGUNDO VIA HARDWARE INTERRUPT
   ;OBSERVE NO 8086 O PINO NMI, ELE ESTA RECEBENDO UM PULSO A CADA UM SEGUNDO, FORÇANDO A INTERRUPÇÃO

   ;RESERVADO PARA VETOR DE INTERRUPCOES
   ORG 0400H

MACRO_INICIALIZA_8253_TIMER0 MACRO HIGH,LOW
   PUSHF
   PUSH AX
   PUSH DX
   
   MOV AL,36H
   MOV DX, ADR_TIMER_CONTROL
   OUT DX,AL

   MOV AL,LOW
   MOV DX, ADR_TIMER_DATA0
   OUT DX,AL

   MOV AL,HIGH
   MOV DX, ADR_TIMER_DATA0
   OUT DX,AL
   
   POP DX
   POP AX
   POPF
ENDM

MACRO_INICIALIZA_8253_TIMER1 MACRO HIGH,LOW
   PUSHF
   PUSH AX
   PUSH DX
   
   MOV AL,76H
   MOV DX, ADR_TIMER_CONTROL
   OUT DX,AL

   MOV AL,LOW
   MOV DX, ADR_TIMER_DATA1
   OUT DX,AL

   MOV AL,HIGH
   MOV DX, ADR_TIMER_DATA1
   OUT DX,AL
   
   POP DX
   POP AX
   POPF
ENDM

MACRO_INICIALIZA_8253_TIMER2 MACRO HIGH,LOW
   PUSHF
   PUSH AX
   PUSH DX
   
   MOV AL,0B6H
   MOV DX, ADR_TIMER_CONTROL
   OUT DX,AL

   MOV AL,LOW
   MOV DX, ADR_TIMER_DATA2
   OUT DX,AL

   MOV AL,HIGH
   MOV DX, ADR_TIMER_DATA2
   OUT DX,AL
   
   POP DX
   POP AX
   POPF
ENDM

INICIO:
     MOV AX,@DATA
     MOV DS,AX
     MOV AX,@STACK
     MOV SS,AX

ZERA:
    MOV DX, IO0
    MOV AL, DIG0
    OUT DX, AL
    
    MOV DX, IO1
    MOV AL, DIG0
    OUT DX, AL
    
    MOV DX, IO2
    MOV AL, DIG0
    OUT DX, AL
    
    MOV DX, IO3
    MOV AL, DIG0
    OUT DX, AL
    
    MOV DX, IO4
    MOV AL, DIG0
    OUT DX, AL
    
    MOV DX, IO5
    MOV AL, DIG0
    OUT DX, AL
    
    JMP SEG_UNI_SHOW

SEG_UNI_PLUS:
    JMP SEG_UNI_PLUS

ZERA_SEG_UNI:
    MOV SEG_UNI,30H
    INC SEG_DEZ
    JMP SEG_DEZ_SHOW
ZERA_SEG_DEZ:
    MOV SEG_DEZ,30H
    INC MIN_UNI
    JMP MIN_UNI_SHOW
ZERA_MIN_UNI:
    MOV MIN_UNI,30H
    INC MIN_DEZ
    JMP MIN_DEZ_SHOW
ZERA_MIN_DEZ:
    MOV MIN_DEZ,30H
    INC HOR_UNI
    JMP HOR_UNI_SHOW
ZERA_HOR_UNI:
    MOV HOR_UNI,30H
    INC HOR_DEZ
    JMP HOR_DEZ_SHOW 
ZERA_HOR_DEZ:
    MOV HOR_DEZ,30H
    MOV HOR_UNI,30H
    MOV MIN_DEZ,30H
    MOV MIN_UNI,30H
    MOV SEG_DEZ,30H
    MOV SEG_UNI,30H
    JMP ZERA

;VERIFICANDO QUE NÚMERO DA UNIDADE DOS SEGUNDOS DEVE SER EXIBIDA
SEG_UNI_SHOW:
    CMP SEG_UNI, 30H
    JE SEG_UNI_0
    CMP SEG_UNI, 31H 
    JE SEG_UNI_1
    CMP SEG_UNI, 32H 
    JE SEG_UNI_2
    CMP SEG_UNI, 33H 
    JE SEG_UNI_3
    CMP SEG_UNI, 34H
    JE SEG_UNI_4
    CMP SEG_UNI, 35H 
    JE SEG_UNI_5
    CMP SEG_UNI, 36H 
    JE SEG_UNI_6
    CMP SEG_UNI, 37H 
    JE SEG_UNI_7
    CMP SEG_UNI, 38H 
    JE SEG_UNI_8
    CMP SEG_UNI, 39H
    JE SEG_UNI_9

;VERIFICANDO QUE NÚMERO DA DEZENA DOS SEGUNDOS DEVE SER EXIBIDA	
SEG_DEZ_SHOW:
    CMP SEG_DEZ, 30H
    JE SEG_DEZ_0
    CMP SEG_DEZ, 31H 
    JE SEG_DEZ_1
    CMP SEG_DEZ, 32H 
    JE SEG_DEZ_2
    CMP SEG_DEZ, 33H 
    JE SEG_DEZ_3
    CMP SEG_DEZ, 34H
    JE SEG_DEZ_4
    CMP SEG_DEZ, 35H 
    JE SEG_DEZ_5
    CMP SEG_DEZ, 36H
    JE SEG_DEZ_6

;VERIFICANDO QUE NÚMERO DA UNIDADE DOS MINUTOS DEVE SER EXIBIDA
MIN_UNI_SHOW:
    CMP MIN_UNI, 30H
    JE MIN_UNI_0
    CMP MIN_UNI, 31H 
    JE MIN_UNI_1
    CMP MIN_UNI, 32H 
    JE MIN_UNI_2
    CMP MIN_UNI, 33H 
    JE MIN_UNI_3
    CMP MIN_UNI, 34H
    JE MIN_UNI_4
    CMP MIN_UNI, 35H 
    JE MIN_UNI_5
    CMP MIN_UNI, 36H 
    JE MIN_UNI_6
    CMP MIN_UNI, 37H 
    JE MIN_UNI_7
    CMP MIN_UNI, 38H 
    JE MIN_UNI_8
    CMP MIN_UNI, 39H
    JE MIN_UNI_9

;VERIFICANDO QUE NÚMERO DA DEZENA DOS MINUTOS DEVE SER EXIBIDA	
MIN_DEZ_SHOW:
    CMP MIN_DEZ, 30H
    JE MIN_DEZ_0
    CMP MIN_DEZ, 31H 
    JE MIN_DEZ_1
    CMP MIN_DEZ, 32H 
    JE MIN_DEZ_2
    CMP MIN_DEZ, 33H 
    JE MIN_DEZ_3
    CMP MIN_DEZ, 34H
    JE MIN_DEZ_4
    CMP MIN_DEZ, 35H 
    JE MIN_DEZ_5
    CMP MIN_DEZ, 36H
    JE MIN_DEZ_6

;VERIFICANDO QUE NÚMERO DA UNIDADE DAS HORAS DEVE SER EXIBIDA
HOR_UNI_SHOW:
    CMP HOR_UNI, 30H
    JE HOR_UNI_0
    CMP HOR_UNI, 31H 
    JE HOR_UNI_1
    CMP HOR_UNI, 32H 
    JE HOR_UNI_2
    CMP HOR_UNI, 33H 
    JE HOR_UNI_3
    CMP HOR_UNI, 34H
    JE HOR_UNI_4
    CMP HOR_UNI, 35H 
    JE HOR_UNI_5
    CMP HOR_UNI, 36H 
    JE HOR_UNI_6
    CMP HOR_UNI, 37H 
    JE HOR_UNI_7
    CMP HOR_UNI, 38H 
    JE HOR_UNI_8
    CMP HOR_UNI, 39H
    JE HOR_UNI_9

;VERIFICANDO QUE NÚMERO DA DEZENA DAS HORAS DEVE SER EXIBIDA
HOR_DEZ_SHOW:
    CMP HOR_DEZ, 30H
    JE HOR_DEZ_0
    CMP HOR_DEZ, 31H 
    JE HOR_DEZ_1
    CMP HOR_DEZ, 32H 
    JE HOR_DEZ_2
    CMP HOR_DEZ, 33H 
    JE HOR_DEZ_3
    CMP HOR_DEZ, 34H
    JE HOR_DEZ_4
    CMP HOR_DEZ, 35H 
    JE HOR_DEZ_5
    CMP HOR_DEZ, 36H
    JE HOR_DEZ_6
    
;MOSTRANDO DÍGITOS DA UNIDADE DOS SEGUNDOS 0-9 
SEG_UNI_0:
    MOV DX, IO0
    MOV AL, DIG0
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_1:
    MOV DX, IO0
    MOV AL, DIG1
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_2:
    MOV DX, IO0
    MOV AL, DIG2
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_3:
    MOV DX, IO0
    MOV AL, DIG3
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_4:
    MOV DX, IO0
    MOV AL, DIG4
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_5:
    MOV DX, IO0
    MOV AL, DIG5
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_6:
    MOV DX, IO0
    MOV AL, DIG6
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_7:
    MOV DX, IO0
    MOV AL, DIG7
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_8:
    MOV DX, IO0
    MOV AL, DIG8
    OUT DX, AL
    JMP SEG_UNI_PLUS
SEG_UNI_9:
    MOV DX, IO0
    MOV AL, DIG9
    OUT DX, AL
    JMP SEG_UNI_PLUS

;MOSTRANDO DÍGITOS DA DEZENA DOS SEGUNDOS 0-6
SEG_DEZ_0:
    MOV DX, IO1
    MOV AL, DIG0
    OUT DX, AL
    JMP SEG_UNI_SHOW
SEG_DEZ_1:
    MOV DX, IO1
    MOV AL, DIG1
    OUT DX, AL
    JMP SEG_UNI_SHOW
SEG_DEZ_2:
    MOV DX, IO1
    MOV AL, DIG2
    OUT DX, AL
    JMP SEG_UNI_SHOW
SEG_DEZ_3:
    MOV DX, IO1
    MOV AL, DIG3
    OUT DX, AL
    JMP SEG_UNI_SHOW
SEG_DEZ_4:
    MOV DX, IO1
    MOV AL, DIG4
    OUT DX, AL
    JMP SEG_UNI_SHOW
SEG_DEZ_5:
    MOV DX, IO1
    MOV AL, DIG5
    OUT DX, AL
    JMP SEG_UNI_SHOW
SEG_DEZ_6:
    MOV DX, IO1
    MOV AL, DIG6
    OUT DX, AL
    JMP SEG_UNI_SHOW

;MOSTRANDO DÍGITOS DA UNIDADE DOS MINUTOS 0-9 
MIN_UNI_0:
    MOV DX, IO2
    MOV AL, DIG0
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_1:
    MOV DX, IO2
    MOV AL, DIG1
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_2:
    MOV DX, IO2
    MOV AL, DIG2
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_3:
    MOV DX, IO2
    MOV AL, DIG3
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_4:
    MOV DX, IO2
    MOV AL, DIG4
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_5:
    MOV DX, IO2
    MOV AL, DIG5
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_6:
    MOV DX, IO2
    MOV AL, DIG6
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_7:
    MOV DX, IO2
    MOV AL, DIG7
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_8:
    MOV DX, IO2
    MOV AL, DIG8
    OUT DX, AL
    JMP SEG_DEZ_SHOW
MIN_UNI_9:
    MOV DX, IO2
    MOV AL, DIG9
    OUT DX, AL
    JMP SEG_DEZ_SHOW

;MOSTRANDO DÍGITOS DA DEZENA DOS MINUTOS 0-6
MIN_DEZ_0:
    MOV DX, IO3
    MOV AL, DIG0
    OUT DX, AL
    JMP MIN_UNI_SHOW
MIN_DEZ_1:
    MOV DX, IO3
    MOV AL, DIG1
    OUT DX, AL
    JMP MIN_UNI_SHOW
MIN_DEZ_2:
    MOV DX, IO3
    MOV AL, DIG2
    OUT DX, AL
    JMP MIN_UNI_SHOW
MIN_DEZ_3:
    MOV DX, IO3
    MOV AL, DIG3
    OUT DX, AL
    JMP MIN_UNI_SHOW
MIN_DEZ_4:
    MOV DX, IO3
    MOV AL, DIG4
    OUT DX, AL
    JMP MIN_UNI_SHOW
MIN_DEZ_5:
    MOV DX, IO3
    MOV AL, DIG5
    OUT DX, AL
    JMP MIN_UNI_SHOW
MIN_DEZ_6:
    MOV DX, IO3
    MOV AL, DIG6
    OUT DX, AL
    JMP MIN_UNI_SHOW

;MOSTRANDO DÍGITOS DA UNIDADE DAS HORAS 0-9 
HOR_UNI_0:
    MOV DX, IO4
    MOV AL, DIG0
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_1:
    MOV DX, IO4
    MOV AL, DIG1
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_2:
    MOV DX, IO4
    MOV AL, DIG2
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_3:
    MOV DX, IO4
    MOV AL, DIG3
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_4:
    MOV DX, IO4
    MOV AL, DIG4
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_5:
    MOV DX, IO4
    MOV AL, DIG5
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_6:
    MOV DX, IO4
    MOV AL, DIG6
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_7:
    MOV DX, IO4
    MOV AL, DIG7
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_8:
    MOV DX, IO4
    MOV AL, DIG8
    OUT DX, AL
    JMP MIN_DEZ_SHOW
HOR_UNI_9:
    MOV DX, IO4
    MOV AL, DIG9
    OUT DX, AL
    JMP MIN_DEZ_SHOW   

;MOSTRANDO DÍGITOS DA DEZENA DAS HORAS 0-6
HOR_DEZ_0:
    MOV DX, IO5
    MOV AL, DIG0
    OUT DX, AL
    JMP HOR_UNI_SHOW
HOR_DEZ_1:
    MOV DX, IO5
    MOV AL, DIG1
    OUT DX, AL
    JMP HOR_UNI_SHOW
HOR_DEZ_2:
    MOV DX, IO5
    MOV AL, DIG2
    OUT DX, AL
    JMP HOR_UNI_SHOW
HOR_DEZ_3:
    MOV DX, IO5
    MOV AL, DIG3
    OUT DX, AL
    JMP HOR_UNI_SHOW
HOR_DEZ_4:
    MOV DX, IO5
    MOV AL, DIG4
    OUT DX, AL
    JMP HOR_UNI_SHOW
HOR_DEZ_5:
    MOV DX, IO5
    MOV AL, DIG5
    OUT DX, AL
    JMP HOR_UNI_SHOW
HOR_DEZ_6:
    MOV DX, IO5
    MOV AL, DIG6
    OUT DX, AL
    JMP HOR_UNI_SHOW  
    
JMP INICIO

INICIALIZA_8251:                                     
   MOV AL,0
   MOV DX, ADR_USART_CMD
   OUT DX,AL
   OUT DX,AL
   OUT DX,AL
   MOV AL,40H
   OUT DX,AL
   MOV AL,4DH
   OUT DX,AL
   MOV AL,37H
   OUT DX,AL
   RET

RECEBE_CARACTER:
   PUSHF
   PUSH DX
AGUARDA_CARACTER:
   MOV DX,ADR_USART_STAT
   IN AL,DX
   TEST AL,2
   JZ AGUARDA_CARACTER
   MOV DX,ADR_USART_DATA
   IN AL,DX
   SHR AL,1
NAO_RECEBIDO:
   POP DX
   POPF
   RET

MANDA_CARACTER:
   PUSHF
   PUSH DX
   PUSH AX  ; SALVA AL   
BUSY:
   MOV DX, ADR_USART_STAT
   IN  AL,DX
   TEST AL,1
   JZ BUSY
   MOV DX, ADR_USART_DATA
   POP AX  ; RESTAURA AL
   OUT DX,AL
   POP DX
   POPF
   RET 
  
BEEP:
      MOV TESTE, 1
      RET

COMPARAR_MINUTO:
       MOV AH,MIN_UNI 
       CMP AH,MIN_UNI_ALARM
       JE BEEP 
 
COMPARAR_MINUTOS:     
        MOV AH,MIN_DEZ
        CMP AH,MIN_DEZ_ALARM
        JE COMPARAR_MINUTO

COMPARAR_HORA:
	MOV AH,HOR_UNI 
	CMP AH,HOR_UNI_ALARM
	JE COMPARAR_MINUTOS

COMPARAR_HORARIO:
	MOV AH, HOR_DEZ
	CMP AH,HOR_DEZ_ALARM
	JE COMPARAR_HORA

.STARTUP
	MOV AX,0000
	MOV DS,AX
	
	MOV WORD PTR PONTEIRO_TRATADOR_INTERRUPCAO, OFFSET INTERRUPT_ONE_SECOND
	MOV WORD PTR PONTEIRO_TRATADOR_INTERRUPCAO + 2, SEG INTERRUPT_ONE_SECOND 

	MOV AX,@DATA
	MOV DS,AX
	MOV AX,@STACK
	MOV SS,AX

	CALL INICIALIZA_8251 

	LEA BX, MSG_INI
	LEA BX, MSG_DESP
	
	CALL ZERA

PROCURA_0:
	MOV AL, [BX]
	CMP AL, 0
	JE ECOAR
	CALL MANDA_CARACTER
	INC BX
	JMP PROCURA_0

ECOAR:
	CALL RECEBE_CARACTER
	CALL MANDA_CARACTER
	JMP ECOAR
		
INTERRUPT_ONE_SECOND:
	PUSHF 
	PUSH AX
	PUSH DX
	CALL COMPARAR_HORARIO
	CMP HOR_DEZ,32H
	JNE CONTINUA
	CMP HOR_UNI,34H
	JE ZERA_HOR_DEZ
	CONTINUA:
	CMP HOR_UNI,39H
	JE ZERA_HOR_UNI
	CMP MIN_DEZ,36H
	JE ZERA_MIN_DEZ
	CMP MIN_UNI,39H
	JE ZERA_MIN_UNI
	CMP SEG_DEZ,36H
	JE ZERA_SEG_DEZ
	CMP SEG_UNI,39H
	JE ZERA_SEG_UNI

	INC SEG_UNI
	JMP SEG_UNI_SHOW
	
	PUSH AX
	PUSH BX
	PUSH CX
	PUSH DI
	PUSH ES ;;FAZ O PUSH DE TODOS OS REGISTOS QUE UTILIZA
	
	POP DX
	POP AX
	POPF
	IRET

;MEUS DADOS
.DATA
    ; VARIAVEIS USADAS PARA ARMAZENAR O HORARIO(HH:MM) INFORMADOS PARA DESPERTAR O RELÓGIO
    MIN_UNI_ALARM DB 30H
    MIN_DEZ_ALARM DB 30H
    HOR_UNI_ALARM DB 30H
    HOR_DEZ_ALARM DB 30H
    
    TESTE DB 0
    NOTA DB 0
    TEMPO_NOTA DB 0
    
    SEG_UNI DB 30H
    SEG_DEZ DB 30H
    MIN_UNI DB 30H
    MIN_DEZ DB 30H
    HOR_UNI DB 30H
    HOR_DEZ DB 30H
    
    MSG_INI  DB "DIGITE O HORARIO INICIAL",13,10,0
    MSG_DESP DB "DIGITE O HORARIO PARA O DESPERTADOR",13,10,0

    SEG_UNI_DES DB 00H
    SEG_DEZ_DES DB 00H
    MIN_UNI_DES DB 00H
    MIN_DEZ_DES DB 00H
    HOR_UNI_DES DB 00H
    HOR_DEZ_DES DB 00H
    
;MILHA PILHA
.STACK
MINHA_PILHA DW 128 DUP(0) 

END